name: Sync Microsoft.Build version in analyzer template with Version.props
on:
  push:
    branches:
      - main
      - SyncTest
    paths:
      - 'eng/Versions.props'

jobs:
  Sync-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.ref }}

    - name: Set baseBranch variable
      id: vars
      run: echo "##[set-output name=baseBranch;]${{ github.ref_name }}"

    - name: Update analyzer template version with version from Versions.props
      id: update-version
      shell: pwsh
      run: |
        try {
            # Define the paths to your XML and JSON files
            $xmlFilePath = "eng/Versions.props"
            $jsonFilePath = "template_feed/content/Microsoft.AnalyzerTemplate/.template.config/template.json"

            # Check if the XML file exists
            if (-Not (Test-Path -Path $xmlFilePath)) {
                throw "Versions.props file not found: $xmlFilePath"
            }

            # Load and parse the XML content
            [xml]$xmlContent = Get-Content -Path $xmlFilePath
            $versionPrefix = [string]$xmlContent.Project.PropertyGroup.VersionPrefix

            # Validate the versionPrefix
            if ([string]::IsNullOrWhiteSpace($versionPrefix)) {
                throw "VersionPrefix is empty or null in the XML file: $xmlFilePath"
            }

            # Check if the JSON file exists
            if (-Not (Test-Path -Path $jsonFilePath)) {
                throw "Analyzer template file not found: $jsonFilePath"
            }

            # Load the JSON template
            $jsonContent = Get-Content -Path $jsonFilePath -Raw | ConvertFrom-Json

            # Update the defaultValue of MicrosoftBuildVersion in the JSON template
            $jsonContent.symbols.MicrosoftBuildVersion.defaultValue = $versionPrefix.Trim()

            # Convert the JSON content back to a string
            $jsonString = $jsonContent | ConvertTo-Json -Depth 10

            # Write the updated JSON back to the file
            Set-Content -Path $jsonFilePath -Value $jsonString
            Write-Output "Updated MicrosoftBuildVersion to $versionPrefix"

            # Set the versionPrefix as an output
            echo "##[set-output name=versionPrefix;]$versionPrefix"
        }
        catch {
            Write-Error "An error occurred: $_"
        }

    - name: Create Pull Request
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');  // Import the fs module
          const newBranch = 'update-msbuild-version-for-analyzer-template';
          const baseBranch = '${{ steps.vars.outputs.baseBranch }}';
          const versionPrefix = '${{ steps.update-version.outputs.versionPrefix }}';
          const commitMessage = `Update MicrosoftBuildVersion to ${versionPrefix}`;
          const filePath = 'template_feed/content/Microsoft.AnalyzerTemplate/.template.config/template.json';
          const fileContent = fs.readFileSync(filePath, 'utf8');
    
          // Main execution
          try {
            // configure git
            await exec.exec(`git config user.name "github-actions"`);
            await exec.exec(`git config user.email "github-actions@github.com"`);
            
            // Create and switch to the new branch
            await exec.exec('git', ['checkout', '-b', newBranch]);
            
            // Stage the changes
            await exec.exec('git', ['add', filePath]);
            
            // Commit the changes
            await exec.exec('git', ['commit', '-m', commitMessage]);

            // Pull the latest changes from the remote branch
            await exec.exec('git', ['pull', '--rebase', 'origin', newBranch]);
        
            // Push the new branch to the remote repository
            await exec.exec('git', ['push', 'origin', newBranch]);
            
            // Create a pull request
            await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Update MicrosoftBuildVersion in analyzer template',
              head: newBranch,
              base: baseBranch,
              body: '[Automated] Update the MicrosoftBuildVersion defaultValue in the template.json.',
            });
          } catch (error) {
            core.setFailed(`Failed to create and push branch: ${error.message}`);
          }

